name: teamcity
services:
  database:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  server:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - "${TEAMCITY_SERVER_PORT}:8111"
    volumes:
      - server-data:/data/teamcity_server/datadir
      - server-logs:/opt/teamcity/logs
    depends_on:
      - database

  agent:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    environment:
      SERVER_URL: ${TEAMCITY_SERVER_URL}
      DOCKER_IN_DOCKER: start
      AGENT_NAME: agent_47
    privileged: true
    volumes:
      - agent-conf:/data/teamcity_agent/conf

volumes:
  pg-data:
  server-data:
  server-logs:
  agent-conf:
